# Generated by Django 3.2.6 on 2024-05-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DicomEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.JSONField(null=True)),
                ('instance_creator_uid', models.CharField(max_length=250, null=True)),
                ('extracted', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('path', models.CharField(max_length=100)),
            ],
        ),
    ]
